[package]
name = "zmq-learn"
version = "0.1.0"
authors = ["laizy"]

[[bin]]
name = "helloclient"
path = "./src/01hello/client.rs"

[[bin]]
name = "helloserver"
path = "./src/01hello/server.rs"

[dependencies.zmq]
version = "0.8"
default-features = false
